version: '3.1'

networks:
  postgres:
    driver: bridge

volumes:
  postgres-data:


services:
  db:
    networks: 
      - postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    networks: 
      - postgres
    ports: 
      - 8080:8080